# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31df0cea45160703a5b0b3e14c0d29af40e339f244a3ec53a8011702438aa744776ff8ba044cae4369f529d796fe10924aeceb2367138697ecf08baa4f52b412

test:
  secret_key_base: 20ace5fc427ae14cf1ca6978ea7a6ebad192b5452004753302efca035f24f543c05238cfa61ee1fff9d15d12218cab972591d173d88739600e98b61dfc81708f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
